name: shinden_mobile
description: Unofficial mobile app for shinden.pl 
publish_to: 'none'
version: 0.0.8+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  http: ^1.2.1
  html: ^0.15.4
  dio: ^5.4.3+1
  deep_pick: ^1.0.0
  file_sizes: ^1.0.6
  pointycastle: ^4.0.0
  open_file_safe_plus : ^0.0.6
  flutter_hls_parser: ^2.0.1
  permission_handler: ^11.3.1
  android_intent_plus: ^5.0.2
  flutter_inappwebview: ^6.0.0
  awesome_notifications: ^0.10.1
  background_downloader: ^9.2.0
  flutter_foreground_task: ^8.8.0
  receive_sharing_intent : ^1.8.1
  
dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/css/
    - assets/js/
    - assets/host.txt
