name: shinden_mobile
description: Unofficial mobile app for shinden.pl 
publish_to: 'none'
version: 0.0.5

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  html: ^0.15.4
  http: ^1.2.1
  dio: ^5.4.3+1
  app_links: ^4.0.1
  deep_pick: ^1.0.0
  file_sizes: ^1.0.6
  pointycastle: ^3.9.0
  open_file_plus: ^3.4.1
  permission_handler: ^11.3.1
  android_intent_plus: ^5.0.2
  flutter_inappwebview: ^6.0.0
  awesome_notifications: ^0.9.3+1
  background_downloader: ^8.4.3
  ffmpeg_kit_flutter_https: ^6.0.3

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/css/
    - assets/js/
    - assets/host.txt
